[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
    "@uniswap/permit2/=lib/permit2/",
    "@uniswap/universal-router/=lib/universal-router/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
sonic_blaze = "${SONIC_BLAZE_RPC}"

[etherscan]
sonic_blaze = { key = "${SONICSCAN_API_KEY}", url = "https://api-testnet.sonicscan.org/api" }
"57054" = { key = "${SONICSCAN_API_KEY}", url = "https://api-testnet.sonicscan.org/api" }